-- USE ['DATABASE NAME'] --
USE tcc;
CREATE TABLE IF NOT EXISTS tb_category(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
)ENGINE=InnoDb DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS tb_levels(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
)ENGINE=InnoDb DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS tb_user(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    tel VARCHAR(13) NOT NULL,
    password VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    category_id INT,
    level INT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES tb_category(id),
    FOREIGN KEY (level) REFERENCES tb_levels(id)
)ENGINE=InnoDb DEFAULT CHARSET=utf8;